"""Add message_id to chat_messages

Revision ID: eb2ec286b7d0
Revises:
Create Date: 2025-02-13 08:51:16.226511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2ec286b7d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('overlay_data', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('overlay_data', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_overlay_data_id'), 'overlay_data', ['id'], unique=False)
    op.add_column('planets', sa.Column('date', sa.DateTime(), nullable=True))
    op.alter_column('planets', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('planets', 'raider_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('planets', 'angle',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('planets', 'distance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_planets_id'), 'planets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planets_id'), table_name='planets')
    op.alter_column('planets', 'distance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('planets', 'angle',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('planets', 'raider_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('planets', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('planets', 'date')
    op.drop_index(op.f('ix_overlay_data_id'), table_name='overlay_data')
    op.alter_column('overlay_data', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('overlay_data', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('overlay_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chat_messages', 'message_id')
    op.drop_index(op.f('ix_admin_buttons_id'), table_name='admin_buttons')
    op.alter_column('admin_buttons', 'data',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(current_timestamp)'), nullable=True),
    sa.Column('twitch_id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=False),
    sa.Column('account_type', sa.TEXT(), nullable=True),
    sa.Column('broadcaster_type', sa.TEXT(), nullable=True),
    sa.Column('profile_image_url', sa.TEXT(), nullable=False),
    sa.Column('account_age', sa.TEXT(), nullable=False),
    sa.Column('follower_date', sa.DATETIME(), nullable=True),
    sa.Column('subscriber_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
